const wordsDatabase = [
    { "id": 1, "word": "apple", "translation": "яблоко", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🍎" },
    { "id": 2, "word": "house", "translation": "дом", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🏠" },
    { "id": 3, "word": "car", "translation": "машина", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🚗" },
    { "id": 4, "word": "bird", "translation": "птица", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🐦" },
    { "id": 5, "word": "fish", "translation": "рыба", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🐟" },
    { "id": 6, "word": "tree", "translation": "дерево", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌳" },
    { "id": 7, "word": "flower", "translation": "цветок", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌼" },
    { "id": 8, "word": "sun", "translation": "солнце", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "☀️" },
    { "id": 9, "word": "moon", "translation": "луна", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌙" },
    { "id": 10, "word": "water", "translation": "вода", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💧" },
    { "id": 11, "word": "food", "translation": "еда", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🍕" },
    { "id": 12, "word": "friend", "translation": "друг", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "👭" },
    { "id": 13, "word": "mother", "translation": "мама", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "👩" },
    { "id": 14, "word": "father", "translation": "папа", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "👨" },
    { "id": 15, "word": "school", "translation": "школа", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🏫" },
    { "id": 16, "word": "city", "translation": "город", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🏙️" },
    { "id": 17, "word": "street", "translation": "улица", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🛣️" },
    { "id": 18, "word": "shop", "translation": "магазин", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🛍️" },
    { "id": 19, "word": "money", "translation": "деньги", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💰" },
    { "id": 20, "word": "time", "translation": "время", "level": "A1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⏰" },
    { "id": 21, "word": "big", "translation": "большой", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🐘" },
    { "id": 22, "word": "small", "translation": "маленький", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🐭" },
    { "id": 23, "word": "good", "translation": "хороший", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👍" },
    { "id": 24, "word": "bad", "translation": "плохой", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👎" },
    { "id": 25, "word": "happy", "translation": "счастливый", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "😊" },
    { "id": 26, "word": "sad", "translation": "грустный", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "😢" },
    { "id": 27, "word": "new", "translation": "новый", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🆕" },
    { "id": 28, "word": "old", "translation": "старый", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👴" },
    { "id": 29, "word": "beautiful", "translation": "красивый", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🌸" },
    { "id": 30, "word": "ugly", "translation": "уродливый", "level": "A1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👹" },
    { "id": 31, "word": "to be", "translation": "быть", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "✨" },
    { "id": 32, "word": "to have", "translation": "иметь", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🫴" },
    { "id": 33, "word": "to do", "translation": "делать", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "⚙️" },
    { "id": 34, "word": "to go", "translation": "идти", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🚶" },
    { "id": 35, "word": "to see", "translation": "видеть", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "👁️" },
    { "id": 36, "word": "to eat", "translation": "есть", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🍽️" },
    { "id": 37, "word": "to drink", "translation": "пить", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🥤" },
    { "id": 38, "word": "to sleep", "translation": "спать", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "😴" },
    { "id": 39, "word": "to run", "translation": "бежать", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🏃" },
    { "id": 40, "word": "to read", "translation": "читать", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📚" },
    { "id": 41, "word": "to work", "translation": "работать", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "💼" },
    { "id": 42, "word": "to play", "translation": "играть", "level": "A1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🎮" },
    { "id": 43, "word": "weather", "translation": "погода", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⛅" },
    { "id": 44, "word": "feeling", "translation": "чувство", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💗" },
    { "id": 45, "word": "decision", "translation": "решение", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🤔" },
    { "id": 46, "word": "experience", "translation": "опыт", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🎓" },
    { "id": 47, "word": "language", "translation": "язык", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🗣️" },
    { "id": 48, "word": "country", "translation": "страна", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🗺️" },
    { "id": 49, "word": "family", "translation": "семья", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "👪" },
    { "id": 50, "word": "holiday", "translation": "праздник", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🎉" },
    { "id": 51, "word": "problem", "translation": "проблема", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⚠️" },
    { "id": 52, "word": "courage", "translation": "храбрость", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🦁" },
    { "id": 53, "word": "failure", "translation": "неудача", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💔" },
    { "id": 54, "word": "freedom", "translation": "свобода", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🕊️" },
    { "id": 55, "word": "journey", "translation": "путешествие", "level": "A2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🧳" },
    { "id": 56, "word": "important", "translation": "важный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "⭐" },
    { "id": 57, "word": "difficult", "translation": "трудный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🧩" },
    { "id": 58, "word": "easy", "translation": "легкий", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "✨" },
    { "id": 59, "word": "interesting", "translation": "интересный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🔍" },
    { "id": 60, "word": "boring", "translation": "скучный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "😴" },
    { "id": 61, "word": "expensive", "translation": "дорогой", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "💎" },
    { "id": 62, "word": "cheap", "translation": "дешевый", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🏷️" },
    { "id": 63, "word": "fast", "translation": "быстрый", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "⚡" },
    { "id": 64, "word": "slow", "translation": "медленный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🐢" },
    { "id": 65, "word": "safe", "translation": "безопасный", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🛡️" },
    { "id": 66, "word": "patient", "translation": "терпеливый", "level": "A2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🧘" },
    { "id": 67, "word": "to understand", "translation": "понимать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🧠" },
    { "id": 68, "word": "to remember", "translation": "помнить", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📝" },
    { "id": 69, "word": "to forget", "translation": "забывать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "💨" },
    { "id": 70, "word": "to believe", "translation": "верить", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🙏" },
    { "id": 71, "word": "to hope", "translation": "надеяться", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🌟" },
    { "id": 72, "word": "to change", "translation": "менять", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🔄" },
    { "id": 73, "word": "to travel", "translation": "путешествовать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "✈️" },
    { "id": 74, "word": "to enjoy", "translation": "наслаждаться", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "😌" },
    { "id": 75, "word": "to explain", "translation": "объяснять", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📢" },
    { "id": 76, "word": "to wait", "translation": "ждать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "⏳" },
    { "id": 77, "word": "to warn", "translation": "предупреждать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "⚠️" },
    { "id": 78, "word": "to prove", "translation": "доказывать", "level": "A2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📜" },
    { "id": 79, "word": "advantage", "translation": "преимущество", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🏆" },
    { "id": 80, "word": "disadvantage", "translation": "недостаток", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⚠️" },
    { "id": 81, "word": "influence", "translation": "влияние", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌊" },
    { "id": 82, "word": "behavior", "translation": "поведение", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🎭" },
    { "id": 83, "word": "environment", "translation": "окружающая среда", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌍" },
    { "id": 84, "word": "government", "translation": "правительство", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🏛️" },
    { "id": 85, "word": "education", "translation": "образование", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🎓" },
    { "id": 86, "word": "knowledge", "translation": "знание", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "📚" },
    { "id": 87, "word": "relationship", "translation": "отношения", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💞" },
    { "id": 88, "word": "opportunity", "translation": "возможность", "level": "B1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🚪" },
    { "id": 89, "word": "responsible", "translation": "ответственный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "✅" },
    { "id": 90, "word": "independent", "translation": "независимый", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🦅" },
    { "id": 91, "word": "confident", "translation": "уверенный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "💪" },
    { "id": 92, "word": "nervous", "translation": "нервный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "😬" },
    { "id": 93, "word": "generous", "translation": "щедрый", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🎁" },
    { "id": 94, "word": "stubborn", "translation": "упрямый", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🐂" },
    { "id": 95, "word": "reliable", "translation": "надёжный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🔒" },
    { "id": 96, "word": "ambitious", "translation": "амбициозный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🚀" },
    { "id": 97, "word": "ancient", "translation": "древний", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🏺" },
    { "id": 98, "word": "modern", "translation": "современный", "level": "B1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "📱" },
    { "id": 99, "word": "to achieve", "translation": "достигать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🏆" },
    { "id": 100, "word": "to improve", "translation": "улучшать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📈" },
    { "id": 101, "word": "to develop", "translation": "развивать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🌱" },
    { "id": 102, "word": "to avoid", "translation": "избегать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🙅" },
    { "id": 103, "word": "to include", "translation": "включать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "➕" },
    { "id": 104, "word": "to prefer", "translation": "предпочитать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "❤️" },
    { "id": 105, "word": "to recommend", "translation": "рекомендовать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📝" },
    { "id": 106, "word": "to survive", "translation": "выживать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🏕️" },
    { "id": 107, "word": "to complain", "translation": "жаловаться", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🗣️" },
    { "id": 108, "word": "to admit", "translation": "признавать", "level": "B1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🤝" },
    { "id": 109, "word": "consequence", "translation": "последствие", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌀" },
    { "id": 110, "word": "contribution", "translation": "вклад", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🤲" },
    { "id": 111, "word": "diversity", "translation": "разнообразие", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌈" },
    { "id": 112, "word": "evidence", "translation": "доказательство", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🔍" },
    { "id": 113, "word": "flexibility", "translation": "гибкость", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌀" },
    { "id": 114, "word": "initiative", "translation": "инициатива", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💡" },
    { "id": 115, "word": "perspective", "translation": "перспектива", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "👓" },
    { "id": 116, "word": "reputation", "translation": "репутация", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⭐" },
    { "id": 117, "word": "strategy", "translation": "стратегия", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "♟️" },
    { "id": 118, "word": "tendency", "translation": "тенденция", "level": "B2", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "📊" },
    { "id": 119, "word": "controversial", "translation": "спорный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "⚖️" },
    { "id": 120, "word": "dramatic", "translation": "драматичный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🎭" },
    { "id": 121, "word": "efficient", "translation": "эффективный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "⚙️" },
    { "id": 122, "word": "inevitable", "translation": "неизбежный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "⏰" },
    { "id": 123, "word": "significant", "translation": "значительный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "📌" },
    { "id": 124, "word": "vulnerable", "translation": "уязвимый", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🪶" },
    { "id": 125, "word": "widespread", "translation": "широко распространённый", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🌍" },
    { "id": 126, "word": "reluctant", "translation": "неохотный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "😐" },
    { "id": 127, "word": "sustainable", "translation": "устойчивый", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🌱" },
    { "id": 128, "word": "transparent", "translation": "прозрачный", "level": "B2", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🔮" },
    { "id": 129, "word": "to acknowledge", "translation": "признавать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🙋" },
    { "id": 130, "word": "to compromise", "translation": "идти на компромисс", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🤝" },
    { "id": 131, "word": "to emphasize", "translation": "подчеркивать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🔴" },
    { "id": 132, "word": "to evaluate", "translation": "оценивать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📊" },
    { "id": 133, "word": "to highlight", "translation": "выделять", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🟡" },
    { "id": 134, "word": "to justify", "translation": "оправдывать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "⚖️" },
    { "id": 135, "word": "to maintain", "translation": "поддерживать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🤲" },
    { "id": 136, "word": "to negotiate", "translation": "вести переговоры", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "💬" },
    { "id": 137, "word": "to perceive", "translation": "воспринимать", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "👁️" },
    { "id": 138, "word": "to reinforce", "translation": "укреплять", "level": "B2", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🏗️" },
    { "id": 139, "word": "ambiguity", "translation": "неоднозначность", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "❓" },
    { "id": 140, "word": "cognition", "translation": "познание", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🧠" },
    { "id": 141, "word": "dilemma", "translation": "дилемма", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "⚖️" },
    { "id": 142, "word": "empathy", "translation": "сочувствие", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "💞" },
    { "id": 143, "word": "fluctuation", "translation": "колебание", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "📈📉" },
    { "id": 144, "word": "implication", "translation": "подтекст", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🔍" },
    { "id": 145, "word": "phenomenon", "translation": "феномен", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🌠" },
    { "id": 146, "word": "redundancy", "translation": "избыточность", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🔄" },
    { "id": 147, "word": "skepticism", "translation": "скептицизм", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🤨" },
    { "id": 148, "word": "vulnerability", "translation": "уязвимость", "level": "C1", "pos": "noun", "mastered": false, "repeatPenalty": 0, "emoji": "🛡️" },
    { "id": 149, "word": "cogent", "translation": "убедительный", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "💪" },
    { "id": 150, "word": "detrimental", "translation": "вредный", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "☠️" },
    { "id": 151, "word": "elusive", "translation": "неуловимый", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👻" },
    { "id": 152, "word": "holistic", "translation": "целостный", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🌍" },
    { "id": 153, "word": "inherent", "translation": "неотъемлемый", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🔗" },
    { "id": 154, "word": "meticulous", "translation": "дотошный", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🔬" },
    { "id": 155, "word": "prevalent", "translation": "распространённый", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🌊" },
    { "id": 156, "word": "stringent", "translation": "строгий", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "📏" },
    { "id": 157, "word": "ubiquitous", "translation": "вездесущий", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "👀" },
    { "id": 158, "word": "versatile", "translation": "универсальный", "level": "C1", "pos": "adjective", "mastered": false, "repeatPenalty": 0, "emoji": "🛠️" },
    { "id": 159, "word": "to articulate", "translation": "ясно выражать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🗣️" },
    { "id": 160, "word": "to corroborate", "translation": "подтверждать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "✅" },
    { "id": 161, "word": "to differentiate", "translation": "различать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🔀" },
    { "id": 162, "word": "to exacerbate", "translation": "обострять", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🔥" },
    { "id": 163, "word": "to facilitate", "translation": "облегчать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🛤️" },
    { "id": 164, "word": "to mitigate", "translation": "смягчать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "☂️" },
    { "id": 165, "word": "to reconcile", "translation": "примирять", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🕊️" },
    { "id": 166, "word": "to scrutinize", "translation": "тщательно изучать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🔍" },
    { "id": 167, "word": "to substantiate", "translation": "обосновывать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "📐" },
    { "id": 168, "word": "to synthesize", "translation": "синтезировать", "level": "C1", "pos": "verb", "mastered": false, "repeatPenalty": 0, "emoji": "🧪" }
  ]
